version: '3.1'

services:
  app:
    build: ./
    restart: always
    links:
      - db
    ports:
      - "8080:80"
    environment:
      DB_USER: root
      DB_PASSWORD: pastin
      DB_HOST: db
      DB_DB: pastin
  db:
    image: mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password --init-file /data/db_init.sql'
    environment:
      MYSQL_DATABASE: pastin
      MYSQL_ROOT_PASSWORD: pastin
    volumes:
      - ./db_init.sql:/data/db_init.sql
      - ./db:/docker-entrypoint-initdb.d/:ro